### ISSUE TITLE
"current" attribute

### ISSUE THREAD

**Issue by LudoFont** [FokkeZB/nl.fokkezb.viewpager#1]
Hi Fokke,

I'm in trouble with the tss attribute "current". 

XML :

```
<Widget` id="pager" `src="nl.fokkezb.viewpager">
  <View title="Retrait">
        <Require id="retrait" src="planning/retrait"/>
    </View>
    <View title="Livraison">
        <Require id="livraison" src="planning/livraison"/>
    </View>
</Widget>
```

TSS :
```
"#pager" : {
    current: 1
}
```

This actually does nothing. Can you help me ?

Note : if i do something like  `$.pager.instance.select(1);`, it doesn't work too ... any idea of what it's come from ?

**Comment by LudoFont** [comment]
Oh god, i just realize that the index start at 1, so to select the 2nd tab, i have to do 

```
"#pager" : {
    current: 2
}
```

Sorry for the disturbing

**Comment by FokkeZB** [comment]
No problem!
