### ISSUE TITLE
tab position on dynamic adding

### ISSUE THREAD

**Issue by LudoFont** [FokkeZB/nl.fokkezb.viewpager#2]
Hi Fokke,

could you take a look about the integration of the tab position on the dynamic .add() ?

I tried this change but without result :

```
$.add = function addView(title, view, position) {
    $.instance.add(title, view, position);
};
```

Thank you,

Ludovic F.

**Comment by FokkeZB** [comment]
You mean to change [these lines](https://github.com/FokkeZB/nl.fokkezb.viewpager/blob/master/nl.fokkezb.viewpager/controllers/widget.js#L49-L57) into this?

```js
$.add = function addView(title, view, position) {

  if (!_.isString(title)) {
    view = title;
    title = _.isString(view.title) ? view.title : '';
  }

  $.instance.add(title, view, position);
};
```

Are you sure the module (version) you use supports this 3rd argument?

**Comment by LudoFont** [comment]
Sadly, this isn't supported in the module version, it may be integrated in a more recent version.
I find an other way to do what i want, so i close the issue.

Thank's

Ludovic F.
